### ISSUE TITLE
replace y_py to pycrdt

### ISSUE THREAD

**Issue by scenaristeur** [jupyter-server/pycrdt-websocket#90]
according to https://github.com/y-crdt/ypy-websocket/issues/93#issuecomment-2021569958

on this page https://jupyter-server.github.io/pycrdt-websocket/usage/client/

y_py should be replaced by pycrdt

and example should be adapted, because pycrdt Doc() does not provide getMap() method

**Comment by scenaristeur** [comment]
hi @davidbrochart thxs for the correction but the new example with
```import asyncio
from websockets import connect
from pycrdt import Doc, Map
from pycrdt_websocket import WebsocketProvider

async def client():
    ydoc = Doc()
    ymap = ydoc.get("map", type=Map)
    async with (
        connect("ws://localhost:1234/my-roomname") as websocket,
        WebsocketProvider(ydoc, websocket),
    ):
        # Changes to remote ydoc are applied to local ydoc.
        # Changes to local ydoc are sent over the WebSocket and
        # broadcast to all clients.
        ymap["key"] = "value"

        await asyncio.Future()  # run forever

asyncio.run(client())
``

give me an error : 

```(.venv) smag@smag-IdeaPad:~/dev/ypu/python$ python client.py 
Traceback (most recent call last):
  File "/home/smag/dev/ypu/python/client.py", line 18, in client
    await asyncio.Future()  # run forever
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f787b2808e0

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/home/smag/dev/ypu/python/client.py", line 20, in <module>
  |     asyncio.run(client())
  |   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
  |     return loop.run_until_complete(main)
  |   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
  |     return future.result()
  |   File "/home/smag/dev/ypu/python/client.py", line 9, in client
  |     async with (
  |   File "/home/smag/dev/ypu/python/.venv/lib/python3.10/site-packages/pycrdt_websocket/websocket_provider.py", line 133, in __aexit__
  |     return await self._exit_stack.__aexit__(exc_type, exc_value, exc_tb)
  |   File "/usr/lib/python3.10/contextlib.py", line 714, in __aexit__
  |     raise exc_details[1]
  |   File "/usr/lib/python3.10/contextlib.py", line 697, in __aexit__
  |     cb_suppress = await cb(*exc_details)
  |   File "/home/smag/dev/ypu/python/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 815, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/smag/dev/ypu/python/.venv/lib/python3.10/site-packages/pycrdt_websocket/websocket_provider.py", line 89, in _run
    |     self._websocket.path,
    | AttributeError: 'ClientConnection' object has no attribute 'path'

``
